# Generated by Django 2.2.6 on 2019-11-11 02:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('emails', '0002_emailmessage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='status',
        ),
    ]
