# Generated by Django 2.2.3 on 2019-07-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
