# Generated by Django 2.2.3 on 2019-07-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='previous_email',
        ),
    ]
