# Generated by Django 2.2.3 on 2019-07-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190715_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default='', max_length=7),
        ),
    ]
