# Generated by Django 2.2.3 on 2019-07-30 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('rooms', '0002_room_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='house', to='houses.House'),
            preserve_default=False,
        ),
    ]
