# Generated by Django 2.2.4 on 2019-08-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('rooms', '0002_auto_20190813_0137'),
	]

	operations = [
		migrations.AlterField(
			model_name='room',
			name='price',
			field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
		),
	]
