# Generated by Django 2.2.3 on 2019-08-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupant',
        ),
    ]
