# Generated by Django 2.2.4 on 2019-09-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0003_auto_20190825_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
