# Generated by Django 2.2.4 on 2019-09-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20190919_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
