# Generated by Django 2.2.4 on 2019-09-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0007_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='move_in_date',
            field=models.DateField(default='1997-11-04'),
        ),
    ]
