# Generated by Django 2.2.4 on 2019-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0008_auto_20190919_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='user',
        ),
    ]
