# Generated by Django 2.2.4 on 2019-09-19 19:45

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('rooms', '0009_auto_20190919_1246'),
	]

	operations = [
		migrations.DeleteModel(
			name='Inquiry',
		),
	]
