# Generated by Django 2.2.4 on 2019-09-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0013_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
