# Generated by Django 2.2.4 on 2019-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rooms', '0015_auto_20190930_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pets_allowed',
            new_name='pet_friendly',
        ),
        migrations.AddField(
            model_name='room',
            name='female_only',
            field=models.BooleanField(default=False, help_text='Only females are allowed to inquire'),
        ),
        migrations.AddField(
            model_name='room',
            name='furnished',
            field=models.BooleanField(default=False, help_text='Room is furnished with at least a bed, mattress, and dresser'),
        ),
        migrations.AddField(
            model_name='room',
            name='utilities_included',
            field=models.BooleanField(default=False, help_text='All utilities are included in the price of rent'),
        ),
    ]
