# Generated by Django 2.2.4 on 2019-08-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('houses', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='house',
			name='place_id',
			field=models.TextField(default=''),
		),
	]
