# Generated by Django 2.2.4 on 2019-08-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('houses', '0006_auto_20190816_1806'),
	]

	operations = [
		migrations.AddField(
			model_name='house',
			name='transit_score_summary',
			field=models.TextField(default=''),
		),
	]
