# Generated by Django 2.2.4 on 2019-08-23 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('houses', '0010_auto_20190823_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
