# Generated by Django 2.2.4 on 2019-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('houses', '0014_auto_20190908_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
