# Generated by Django 2.2.4 on 2019-09-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_house_is_accessible'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='open_to_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_accessible',
            field=models.BooleanField(default=False, verbose_name='Accessible'),
        ),
    ]
