# Generated by Django 2.2.4 on 2019-10-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_auto_20190930_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='num_female',
        ),
        migrations.RemoveField(
            model_name='house',
            name='num_male',
        ),
    ]
