# Generated by Django 2.2.4 on 2019-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('houses', '0020_auto_20191001_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='num_bathrooms',
            field=models.IntegerField(default=0, verbose_name='Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_parking_spaces',
            field=models.IntegerField(default=0, verbose_name='Number of Parking Spaces'),
        ),
        migrations.AlterField(
            model_name='house',
            name='num_rooms',
            field=models.IntegerField(default=0, verbose_name='Number of Rooms'),
        ),
    ]
