# Generated by Django 2.2.7 on 2019-11-23 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_auto_20191001_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='garbage_day_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='garbage_frequency',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='house',
            name='last_garbage_day',
            field=models.DateField(default='1997-11-04'),
        ),
        migrations.AddField(
            model_name='house',
            name='next_garbage_day',
            field=models.DateField(default='1997-11-04'),
        ),
    ]
