# Generated by Django 2.2.4 on 2019-08-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='house',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillSet',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
