# Generated by Django 2.2.4 on 2019-08-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_billset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billset',
            name='month',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
