# Generated by Django 2.2.4 on 2019-09-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20190828_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='file',
            field=models.FileField(default='#', upload_to=''),
        ),
    ]
