# Generated by Django 2.2.4 on 2019-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bills', '0010_auto_20190902_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='file',
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(),
        ),
    ]
