# Generated by Django 2.2.4 on 2019-09-02 17:16

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('bills', '0011_auto_20190902_1228'),
	]

	operations = [
		migrations.RemoveField(
			model_name='bill',
			name='is_approved',
		),
	]
