# Generated by Django 2.2.7 on 2019-12-18 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bills', '0014_auto_20191012_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['date']},
        ),
    ]
