# Generated by Django 2.2.4 on 2019-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
