# Generated by Django 2.2.4 on 2019-09-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phonenumberverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumberVerification',
        ),
    ]
