# Generated by Django 2.2.4 on 2019-09-16 04:07

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('accounts', '0007_auto_20190915_2331'),
	]

	operations = [
		migrations.DeleteModel(
			name='PhoneNumberVerification',
		),
	]
