# Generated by Django 2.2.4 on 2019-08-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190819_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promotional_emails',
            field=models.BooleanField(default=False),
        ),
    ]
