# Generated by Django 2.2.4 on 2019-08-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_promotional_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='promotional_emails',
        ),
    ]
