# Generated by Django 2.2.4 on 2019-09-23 01:26

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('accounts', '0008_delete_phonenumberverification'),
	]

	operations = [
		migrations.RenameField(
			model_name='user',
			old_name='bill_contact',
			new_name='general_contact',
		),
	]
