# Generated by Django 2.2.4 on 2019-08-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_promotional_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_houses',
            field=models.IntegerField(default=1),
        ),
    ]
