# Generated by Django 2.2.4 on 2019-09-30 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_auto_20190922_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='score',
            new_name='_score',
        ),
    ]
