# Generated by Django 2.2.4 on 2019-08-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_max_houses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_houses',
        ),
    ]
