# Generated by Django 2.2.4 on 2019-09-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190930_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_member',
            field=models.BooleanField(default=True),
        ),
    ]
