# Generated by Django 2.2.6 on 2019-11-11 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_premium_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_unsubscribe_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
