# Generated by Django 2.2.6 on 2019-11-11 02:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user__unsubscribe_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_unsubscribe_key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
