# Generated by Django 2.2.6 on 2019-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191110_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_unsubscribe_key',
        ),
    ]
