# Generated by Django 2.2.9 on 2019-12-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0014_remove_user__unsubscribe_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
