# Generated by Django 2.2.3 on 2019-07-25 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190725_1326'),
        ('utils', '0002_auto_20190725_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='room',
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.Image')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.Room')),
            ],
            bases=('utils.image',),
        ),
    ]
