# Generated by Django 2.2.4 on 2019-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(default='', max_length=254)),
                ('subject', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
