# Generated by Django 2.2.4 on 2019-09-23 01:18

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('main', '0001_initial'),
	]

	operations = [
		migrations.RenameModel(
			old_name='BillSet',
			new_name='ContactMessage',
		),
	]
