# Generated by Django 2.2.4 on 2019-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20190922_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(default='', max_length=254)),
                ('subject', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
