# Generated by Django 2.2.7 on 2019-12-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bugreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugReport',
        ),
    ]
