# Generated by Django 3.0.3 on 2020-02-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_bugreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip',
        ),
    ]
