# Generated by Django 3.0.3 on 2020-02-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_fingerprint_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='edited_at',
        ),
    ]
