# Generated by Django 3.0.3 on 2020-02-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_remove_fingerprint_edited_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip',
            new_name='address',
        ),
    ]
