# Generated by Django 2.2.3 on 2019-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='postal_code',
            field=models.CharField(max_length=7),
        ),
    ]
