# Generated by Django 2.2.3 on 2019-07-23 19:49

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('houses', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='house',
			name='kijiji_link',
		),
	]
