# Generated by Django 2.2.3 on 2019-07-17 03:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20190716_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='country',
            field=django_countries.fields.CountryField(default='CA', max_length=2),
        ),
    ]
