# Generated by Django 2.2.3 on 2019-07-16 02:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0002_auto_20190715_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AddField(
            model_name='house',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 22, 52, 10, 63375)),
        ),
        migrations.AlterField(
            model_name='house',
            name='kijiji_link',
            field=models.URLField(default=''),
        ),
    ]
