# Generated by Django 2.2.3 on 2019-07-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20190725_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
