# Generated by Django 2.2.3 on 2019-07-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tenant',
        ),
    ]
