# Generated by Django 2.2.4 on 2019-09-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_billfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
