# Generated by Django 2.2.4 on 2019-09-16 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('utils', '0005_delete_email'),
	]

	operations = [
		migrations.CreateModel(
			name='PhoneNumberVerification',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('phone_number', models.IntegerField(default=-1)),
				('code', models.IntegerField(default=-1)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
		),
	]
