# Generated by Django 3.0.3 on 2020-02-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_houseimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP',
        ),
    ]
