# Generated by Django 3.0.3 on 2020-02-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_bannedfingerprint_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='user',
        ),
        migrations.DeleteModel(
            name='BannedFingerprint',
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
