# Generated by Django 2.2.7 on 2019-11-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0021_auto_20191001_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_garbage_day', models.DateField()),
                ('next_garbage_day', models.DateField()),
                ('garbage_frequency', models.DurationField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
    ]
