# Generated by Django 2.2.7 on 2019-11-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('garbageday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbageday',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
    ]
