# Generated by Django 2.2.7 on 2019-11-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageday', '0002_auto_20191128_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbageday',
            name='garbage_frequency',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
