# Generated by Django 3.0.7 on 2020-06-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageday', '0004_auto_20191129_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbageday',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
