# Generated by Django 3.0.7 on 2020-06-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageday', '0005_garbageday_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbageday',
            name='last_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
